# Generated by Django 5.2.8 on 2026-01-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_scope_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='تفعيل النطاقات')),
            ],
            options={
                'verbose_name': 'إعدادات النطاق',
                'verbose_name_plural': 'إعدادات النطاق',
            },
        ),
    ]
